### ISSUE TITLE
Speed drop after a few seconds

### ISSUE THREAD

**Issue by multispeed** [tpill90/battlenet-lancache-prefill#104]
**Describe the bug**
I prefilled overwatch into lancache and started a download from my pc. It starts with 70 MBps and then drops dramatically after a few seconds to 2-3MBps. 

**Additional Details**
 - Platform you are running BattleNetPrefill on:  Linux Ubuntu server 23.04
- I then tried filling a game into the lancache steam cache and downloading that. And that game downloaded full speed for the total download
 - Region : Amsterdam

**Comment by tpill90** [comment]
What language do you have the game set to? Is it Dutch?

**Comment by multispeed** [comment]
> What language do you have the game set to? Is it Dutch?

My battle.net launcher is in english, but my region is the netherlands.

Could this be the issue?

**Comment by tpill90** [comment]
It could very well be the issue. I'll try to reproduce later

**Comment by tpill90** [comment]
I'm able to reproduce the speed drop, however while watching my `access.log` there are no `MISS` requests at all.  This has to be some sort of issue with the Overwatch installer itself.

**Comment by multispeed** [comment]
Hi Tim,

Thank you for investigating, no solution at this point i presume? Should other games from blizzard download  correctly from the cache?

**Comment by tpill90** [comment]
Presumably everything should download from the cache with no issue. I tried WoW and it looks like it has the same issue with no misses. 

I didn't try any other ones because I don't honestly use battlenet anymore. I'd be curious to see if the same issue persists when the lancache is disabled. 

If I had to wager a guess this is probably another interaction with battlenet not playing nicely with lancache. One thing to consider is that it is downloading at speeds that would normally not be attainable, and could be causing the battlenet client to choke
