### ISSUE TITLE
Unverified .dylib and ./BattleNetPrefill files

### ISSUE THREAD

**Issue by skhati1** [tpill90/battlenet-lancache-prefill#17]
Seems like OSX is flagging each file (in some cases the same DLL multiple times) as coming from an unverified developer. Maybe there's a way to sign it so it doesn't get flagged. Not a blocker since I can go to System Preferences -> Security and Privacy -> General Tab and “Allow Anyway” each instance. This does happen once you can get the CLI running and actually try to download a cache additionally so just a bit of a speed bump.

<img width="260" alt="BattleNetPrefill cannot be" src="https://user-images.githubusercontent.com/10587654/170027639-67cdbf7f-d353-4ae5-ba01-a25c195b6fc6.png">

**Comment by tpill90** [comment]
I did some more digging into this, and it looks like there is ultimately nothing that can be done about this, at least without buying a Mac + an Apple Developer license.  There is also a sizeable amount of work that would need to be done on build pipelines to support this.  
Closing this issue since there is nothing more that can be done on it.
